In [2]:
from pathlib import Path
import pandas as pd

In [3]:
# Для отображения числе не в экспоненциальном виде, а обрезанными до двух знаков после запятой
pd.options.display.float_format = '{:.2f}'.format

In [4]:
project_dir = Path.cwd().parent
data_path = project_dir / 'data' / 'marketplace.csv'
marketplace = pd.read_csv(data_path)
marketplace.head()

,user_id,platform_num,first_login,reg_dt,browser,first_buy,target,total_buy,total_return
0,user_000000,12,2025-03-22,2024-08-17,browser_00,2025-03-22,0.00,85.33,0.00
1,user_000001,1,2025-05-05,2025-05-15,browser_01,2025-05-20,0.00,21.82,0.00
2,user_000002,5,2025-01-19,2025-01-23,browser_02,2025-02-20,0.30,194.61,485.00
3,user_000003,3,2025-03-15,2023-09-05,browser_02,NaN,0.00,138.78,0.00
4,user_000004,1,2025-05-05,2025-05-14,browser_00,2025-05-11,0.00,16.33,0.00

In [4]:
marketplace.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25335 entries, 0 to 25334
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       25335 non-null  object
 1   platform_num  25335 non-null  int64
 2   first_login   25335 non-null  object
 3   reg_dt        25331 non-null  object
 4   browser       25335 non-null  object
 5   first_buy     24361 non-null  object
 6   target        25335 non-null  float64
 7   total_buy     25335 non-null  float64
 8   total_return  25335 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 1.7+ MB

In [9]:
marketplace.describe()

       platform_num   target  total_buy  total_return
count      25335.00 25335.00   25335.00      25335.00
mean           6.47     0.00     898.55        334.08
std           17.02     0.25    6815.55       2882.91
min            1.00    -3.43       0.00          0.00
25%            2.00     0.00      19.36          0.00
50%            3.00     0.00      52.72          0.00
75%            6.00     0.00     203.53          0.00
max          674.00     0.30  490447.99     207893.84

# Анализ пользователей у которых есть возрвраты

In [21]:
df_with_returns = marketplace[marketplace["total_return"] != 0 ]
df_with_returns.describe()

       platform_num  target  total_buy  total_return
count       5402.00 5402.00    5402.00       5402.00
mean          12.31   -0.02    3438.65       1566.82
std           32.06    0.42   14330.97       6087.10
min            1.00   -3.43       0.00         20.00
25%            2.00    0.00      76.82         75.00
50%            5.00    0.00     373.38        229.06
75%            9.00    0.00    1803.39        893.30
max          674.00    0.30  490447.99     207893.84

## Изучение признака platform_num

In [23]:
df_with_returns[df_with_returns["platform_num"] == df_with_returns["platform_num"].max()]

,user_id,platform_num,first_login,reg_dt,browser,first_buy,target,total_buy,total_return
1927,user_001925,674,2024-11-12,2024-07-25,browser_03,2024-08-03,0.30,45877.83,24302.00

In [24]:
df_with_returns.sort_values("platform_num", ascending=False).head(10)

,user_id,platform_num,first_login,reg_dt,browser,first_buy,target,total_buy,total_return
1927,user_001925,674,2024-11-12,2024-07-25,browser_03,2024-08-03,0.30,45877.83,24302.00
14553,user_014550,647,2024-10-02,2024-09-05,browser_03,2024-09-21,-0.00,15754.61,10643.36
3067,user_003065,542,2024-10-11,2024-07-26,browser_02,2024-09-15,0.10,66582.73,20983.01
18597,user_018594,540,2024-12-14,2024-12-01,browser_03,2024-11-26,0.30,18992.27,10651.05
17874,user_017871,475,2024-11-02,2024-10-31,browser_03,2024-12-09,0.22,20179.29,4050.00
10881,user_010878,399,2025-03-30,2024-01-27,browser_03,2025-03-16,0.30,5364.42,2498.61
7787,user_007784,391,2024-12-05,2024-12-09,browser_06,2024-12-15,-2.03,3425.46,2120.53
435,user_000433,358,2024-10-02,2024-10-03,browser_03,2024-09-29,0.00,5073.51,3175.00
12776,user_012773,352,2025-03-22,2022-12-28,browser_03,2025-03-16,0.00,9723.93,9682.00
18049,user_018046,349,2024-09-26,2024-01-11,browser_09,2024-01-21,0.00,55602.37,19282.62

Топ-10 по количеству устройств выглядит неестественным.
### Список гипотез:
- Гипотеза А: технический баг
Количество устройств считается неправильно
- Гипотеза B: мошеннические аккаунты
- Гипотеза C: коллективные аккаунты

#### Отличительные признаки
Топ-10 по количеству устройств выше 75-го перцентиля по total_buy и total_return.