In [1]:
from pathlib import Path
import pandas as pd

In [2]:
# Для отображения числе не в экспоненциальном виде, а обрезанными до двух знаков после запятой
pd.options.display.float_format = '{:.2f}'.format

In [3]:
project_dir = Path.cwd().parent
data_path = project_dir / 'data' / 'marketplace.csv'
marketplace = pd.read_csv(data_path)
marketplace.head()

,user_id,platform_num,first_login,reg_dt,browser,first_buy,target,total_buy,total_return
0,user_000000,12,2025-03-22,2024-08-17,browser_00,2025-03-22,0.00,85.33,0.00
1,user_000001,1,2025-05-05,2025-05-15,browser_01,2025-05-20,0.00,21.82,0.00
2,user_000002,5,2025-01-19,2025-01-23,browser_02,2025-02-20,0.30,194.61,485.00
3,user_000003,3,2025-03-15,2023-09-05,browser_02,NaN,0.00,138.78,0.00
4,user_000004,1,2025-05-05,2025-05-14,browser_00,2025-05-11,0.00,16.33,0.00

In [4]:
marketplace.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25335 entries, 0 to 25334
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       25335 non-null  object
 1   platform_num  25335 non-null  int64
 2   first_login   25335 non-null  object
 3   reg_dt        25331 non-null  object
 4   browser       25335 non-null  object
 5   first_buy     24361 non-null  object
 6   target        25335 non-null  float64
 7   total_buy     25335 non-null  float64
 8   total_return  25335 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 1.7+ MB

In [5]:
marketplace.describe()

       platform_num   target  total_buy  total_return
count      25335.00 25335.00   25335.00      25335.00
mean           6.47     0.00     898.55        334.08
std           17.02     0.25    6815.55       2882.91
min            1.00    -3.43       0.00          0.00
25%            2.00     0.00      19.36          0.00
50%            3.00     0.00      52.72          0.00
75%            6.00     0.00     203.53          0.00
max          674.00     0.30  490447.99     207893.84